/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.StavkaRezervacije;
import klase.Vozilo;
import komunikacija.Komunikacija;
import konstante.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class DialogKreirajStavkuRez extends javax.swing.JDialog {

    /**
     * Creates new form DialogKreirajStavkuRez
     */
    
  

    
    public DialogKreirajStavkuRez(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        
        
        popuniCBVozila();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbVozila = new javax.swing.JComboBox<>();
        txtBrojDana = new javax.swing.JTextField();
        lblVoziloID = new javax.swing.JLabel();
        ftxtIznosVozila = new javax.swing.JFormattedTextField();
        ftxtIznosStavke = new javax.swing.JFormattedTextField();
        btnIzaberiVozilo = new javax.swing.JButton();
        btnIzracunajIznosStavke = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDodajStavku = new javax.swing.JButton();
        btnNapraviStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        lblRezID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Vehicle:");

        jLabel2.setText("Reminder:");

        jLabel3.setText("Cost:");

        jLabel4.setText("Days:");

        jLabel5.setText("Item cost:");

        jLabel6.setText("Vehicle ID:");

        cmbVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVozilaActionPerformed(evt);
            }
        });

        ftxtIznosVozila.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00"))));

        ftxtIznosStavke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00"))));

        btnIzaberiVozilo.setText("Select");
        btnIzaberiVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiVoziloActionPerformed(evt);
            }
        });

        btnIzracunajIznosStavke.setText("Calculate");
        btnIzracunajIznosStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajIznosStavkeActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDodajStavku.setText("Add more");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnNapraviStavku.setText("Insert");
        btnNapraviStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapraviStavkuActionPerformed(evt);
            }
        });

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane1.setViewportView(txtNapomena);

        jLabel7.setText("Reservation ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNapraviStavku)
                .addGap(18, 18, 18)
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVoziloID)
                            .addComponent(cmbVozila, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBrojDana)
                            .addComponent(ftxtIznosVozila)
                            .addComponent(ftxtIznosStavke)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzaberiVozilo)
                            .addComponent(btnIzracunajIznosStavke)))
                    .addComponent(lblRezID))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzaberiVozilo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtIznosVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzracunajIznosStavke))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtIznosStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblVoziloID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblRezID))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnNapraviStavku))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNapraviStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapraviStavkuActionPerformed
        
        if (txtBrojDana.getText().isEmpty() || txtNapomena.getText().isEmpty()
                || ftxtIznosVozila.getText().isEmpty() || ftxtIznosStavke.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!");
            return;
        }
        
        Vozilo vozilo = (Vozilo) cmbVozila.getSelectedItem();
        String napomena = txtNapomena.getText();
        double cena = (double) ftxtIznosVozila.getValue();
        int dani = Integer.parseInt(txtBrojDana.getText());
        double iznosStavke = (double) ftxtIznosStavke.getValue();
        int voziloID = vozilo.getIdVozilo();
        int idRez = Integer.valueOf(lblRezID.getText());
        
        
        StavkaRezervacije stavka = new StavkaRezervacije( idRez, -1, vozilo.getModel(), napomena, cena, dani, iznosStavke, voziloID, vozilo);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.KREIRAJ_STAVKU_REZ);
        kz.setParametar(stavka);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) so.getOdgovor();

        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Item created!");
            
            

        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
        
    }//GEN-LAST:event_btnNapraviStavkuActionPerformed

    private void btnIzaberiVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiVoziloActionPerformed
        
        Vozilo auto = (Vozilo) cmbVozila.getSelectedItem();
        ftxtIznosVozila.setValue(auto.getCenaDana());
        lblVoziloID.setText( String.valueOf(auto.getIdVozilo()));
        
        
        
    }//GEN-LAST:event_btnIzaberiVoziloActionPerformed

    private void btnIzracunajIznosStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajIznosStavkeActionPerformed
        
        if(ftxtIznosVozila.getText().isEmpty() || txtBrojDana.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill the fields!");
            return;
        }
        
        double cena = Double.valueOf(ftxtIznosVozila.getText());
        int dani = Integer.parseInt(txtBrojDana.getText());
        ftxtIznosStavke.setValue(dani*cena);
        
    }//GEN-LAST:event_btnIzracunajIznosStavkeActionPerformed

    private void cmbVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVozilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVozilaActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        txtNapomena.setText("");
        txtBrojDana.setText("");
        ftxtIznosStavke.setText("");
        ftxtIznosVozila.setText("");
        lblVoziloID.setText("");
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogKreirajStavkuRez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogKreirajStavkuRez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogKreirajStavkuRez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogKreirajStavkuRez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Rezervacija rez = ;
//                DialogKreirajStavkuRez dialog = new DialogKreirajStavkuRez(new javax.swing.JDialog(), true, rez);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzaberiVozilo;
    private javax.swing.JButton btnIzracunajIznosStavke;
    private javax.swing.JButton btnNapraviStavku;
    private javax.swing.JComboBox<Vozilo> cmbVozila;
    private javax.swing.JFormattedTextField ftxtIznosStavke;
    private javax.swing.JFormattedTextField ftxtIznosVozila;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRezID;
    private javax.swing.JLabel lblVoziloID;
    private javax.swing.JTextField txtBrojDana;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables

    private void popuniCBVozila() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_VOZILA);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Vozilo> vozila = (ArrayList<Vozilo>) so.getOdgovor();

        cmbVozila.removeAllItems();

        for (Vozilo v : vozila) {
            cmbVozila.addItem(v);
        }
    }

    void postaviId(int id) {
        lblRezID.setText(String.valueOf(id));
    }

    
}
