/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import javax.swing.JOptionPane;
import klase.Zaposleni;
import komunikacija.Komunikacija;
import konstante.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;



/**
 *
 * @author Miloš
 */
public class DialogIzmeniZaposlenog extends javax.swing.JDialog {

    /**
     * Creates new form DialogIzmeni
     */
    
    
    public DialogIzmeniZaposlenog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIzmeniImeZaposlenog = new javax.swing.JTextField();
        txtIzmeniPrezimeZaposlenog = new javax.swing.JTextField();
        txtIzmeniUsernameZaposlenog = new javax.swing.JTextField();
        btnSacuvajIzmeneZaposlenog = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make changes to employee ");

        jLabel1.setText("Name:");

        jLabel2.setText("Surname:");

        jLabel3.setText("Username:");

        btnSacuvajIzmeneZaposlenog.setText("Save changes");
        btnSacuvajIzmeneZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneZaposlenogActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbID)
                        .addGap(65, 65, 65)
                        .addComponent(btnSacuvajIzmeneZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIzmeniImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIzmeniPrezimeZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(txtIzmeniUsernameZaposlenog)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIzmeniImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIzmeniPrezimeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIzmeniUsernameZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajIzmeneZaposlenog)
                    .addComponent(jLabel5)
                    .addComponent(lbID))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajIzmeneZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIzmeneZaposlenogActionPerformed
        
        if (txtIzmeniImeZaposlenog.getText().isEmpty() || txtIzmeniPrezimeZaposlenog.getText().isEmpty()
                || txtIzmeniUsernameZaposlenog.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!");
            return;
        }
        
        int id = Integer.valueOf(lbID.getText());
        String ime = txtIzmeniImeZaposlenog.getText();
        String prezime = txtIzmeniPrezimeZaposlenog.getText();
        String korisnickoIme = txtIzmeniUsernameZaposlenog.getText();

        Zaposleni zaposlen = new Zaposleni(id, ime, prezime, null, korisnickoIme);
        
        

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.IZMENI_ZAPOSLENOG);
        kz.setParametar(zaposlen);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean izmenjen = (boolean) so.getOdgovor();

        if (izmenjen) {
            JOptionPane.showMessageDialog(this, "Employee is edited!");
            
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
        
    }//GEN-LAST:event_btnSacuvajIzmeneZaposlenogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogIzmeniZaposlenog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogIzmeniZaposlenog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogIzmeniZaposlenog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogIzmeniZaposlenog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogIzmeniZaposlenog dialog = new DialogIzmeniZaposlenog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajIzmeneZaposlenog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbID;
    private javax.swing.JTextField txtIzmeniImeZaposlenog;
    private javax.swing.JTextField txtIzmeniPrezimeZaposlenog;
    private javax.swing.JTextField txtIzmeniUsernameZaposlenog;
    // End of variables declaration//GEN-END:variables

    public void postaviId(int id) {
        lbID.setText(String.valueOf(id)); // Ako imaš JLabel za ID zaposlenog
    }

    public void postaviIme(String ime) {
        txtIzmeniImeZaposlenog.setText(ime); // Postavlja ime u JTextField
    }

    public void postaviPrezime(String prezime) {
        txtIzmeniPrezimeZaposlenog.setText(prezime); // Postavlja prezime u JTextField
    }

    public void postaviKorisnickoIme(String korisnickoIme) {
        txtIzmeniUsernameZaposlenog.setText(korisnickoIme); // Postavlja korisničko ime u JTextField
    }

//    public void postaviLozinku(String lozinka) {
//        txtIzmeniUsernameZaposlenog.setText(lozinka); 
//    }
}
