/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.Mesto;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.TabelaMesto;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class FormaMesto extends javax.swing.JFrame {

    /**
     * Creates new form FormaMesto
     */
    public FormaMesto() {
        initComponents();
        setLocationRelativeTo(null);
        
        tblMesta.setModel(new TabelaMesto());
        
        popuniTabeluMesta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesta = new javax.swing.JTable();
        lblMesto = new javax.swing.JLabel();
        txtNovoMesto = new javax.swing.JTextField();
        lblAdresa = new javax.swing.JLabel();
        txtNovaAdresa = new javax.swing.JTextField();
        btnDodajMesto = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnOsveziTabeluMesta = new javax.swing.JButton();
        btnObrisiMesto = new javax.swing.JButton();
        btnIzmeniMesto = new javax.swing.JButton();
        btnPretraziMesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPretraziMesto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPretragaPoID = new javax.swing.JTextField();
        btnPretraziMestoPoID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMesta);

        lblMesto.setText("City:");

        lblAdresa.setText("Adress:");

        btnDodajMesto.setText("Insert");
        btnDodajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMestoActionPerformed(evt);
            }
        });

        btnNazad.setText("Back");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnOsveziTabeluMesta.setText("Refresh");
        btnOsveziTabeluMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluMestaActionPerformed(evt);
            }
        });

        btnObrisiMesto.setText("Delete");
        btnObrisiMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiMestoActionPerformed(evt);
            }
        });

        btnIzmeniMesto.setText("Change");
        btnIzmeniMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniMestoActionPerformed(evt);
            }
        });

        btnPretraziMesto.setText("Search");
        btnPretraziMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziMestoActionPerformed(evt);
            }
        });

        jLabel1.setText("City:");

        jLabel2.setText("ID:");

        btnPretraziMestoPoID.setText("Search");
        btnPretraziMestoPoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziMestoPoIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraziMesto)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziMesto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnOsveziTabeluMesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiMesto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretragaPoID)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziMestoPoID)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(btnDodajMesto))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNovoMesto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNovaAdresa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdresa)
                                    .addComponent(lblMesto))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIzmeniMesto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNazad, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOsveziTabeluMesta)
                            .addComponent(btnObrisiMesto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNovoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNovaAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDodajMesto)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeniMesto)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraziMesto)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraziMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraziMestoPoID)
                    .addComponent(jLabel2)
                    .addComponent(txtPretragaPoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        GlavnaForma gf = new GlavnaForma();
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnDodajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMestoActionPerformed
        if (txtNovoMesto.getText().isEmpty() || txtNovaAdresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!");
            return;
        }

        
        String mesto = txtNovoMesto.getText();
        String adresa = txtNovaAdresa.getText();
        
        
        Mesto m = new Mesto(-1, mesto, adresa);

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.DODAJ_MESTO);
        kz.setParametar(m);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) so.getOdgovor();

        if (uspesno) {
            JOptionPane.showMessageDialog(this, "New place created!");
            
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnDodajMestoActionPerformed

    private void btnOsveziTabeluMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluMestaActionPerformed
        popuniTabeluMesta();
    }//GEN-LAST:event_btnOsveziTabeluMestaActionPerformed

    private void btnObrisiMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiMestoActionPerformed
        int row = tblMesta.getSelectedRow();

        if (row != -1) {
            TabelaMesto tm = (TabelaMesto) tblMesta.getModel();
            Object id = tblMesta.getValueAt(row, 2);
            tm.obrisiSmenu(row);

            

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_MESTO);
            kz.setParametar(id);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            tm.fireTableDataChanged();

            boolean obrisan = (boolean) so.getOdgovor();

            if (obrisan) {
                JOptionPane.showMessageDialog(this, "Place deleted!");

                

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnObrisiMestoActionPerformed

    private void btnIzmeniMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniMestoActionPerformed
        int row = tblMesta.getSelectedRow();
        if (row != -1) {
            TabelaMesto tm = (TabelaMesto) tblMesta.getModel();
            int id = (int) tblMesta.getValueAt(row, 2);
            String mesto = (String) tblMesta.getValueAt(row, 0);              // mesto je u koloni 0
            String adresa = (String) tblMesta.getValueAt(row, 1);          // adresa je u koloni 1
            

            DialogIzmeniMesto dim = new DialogIzmeniMesto(this, true);
            
            
            dim.postaviMesto(mesto);
            dim.postaviAdresu(adresa);
            dim.postaviID(id);
            
            
            
            dim.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnIzmeniMestoActionPerformed

    private void btnPretraziMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziMestoActionPerformed
        if(txtPretraziMesto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter place!");
            return;
        }
        
        String grad = txtPretraziMesto.getText();
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_MESTA);
        kz.setParametar(grad);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Mesto> pretrazenoMesto = (ArrayList<Mesto>) so.getOdgovor();

        tblMesta.removeAll();

         
        TabelaMesto tm = (TabelaMesto) tblMesta.getModel();
        tm.setPretragaMesto(pretrazenoMesto);
    }//GEN-LAST:event_btnPretraziMestoActionPerformed

    private void btnPretraziMestoPoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziMestoPoIDActionPerformed
        if(txtPretragaPoID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter place ID!");
            return;
        }
        
        int id = Integer.parseInt(txtPretragaPoID.getText());
        
        
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_IDMESTA);
        kz.setParametar(id);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        
        
        ArrayList<Mesto> pretraziM = (ArrayList<Mesto>) so.getOdgovor();

        tblMesta.removeAll();

        
         
        TabelaMesto tm = (TabelaMesto) tblMesta.getModel();
        tm.setPretragaMesto(pretraziM);
    }//GEN-LAST:event_btnPretraziMestoPoIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaMesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaMesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaMesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaMesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaMesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajMesto;
    private javax.swing.JButton btnIzmeniMesto;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiMesto;
    private javax.swing.JButton btnOsveziTabeluMesta;
    private javax.swing.JButton btnPretraziMesto;
    private javax.swing.JButton btnPretraziMestoPoID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblMesto;
    private javax.swing.JTable tblMesta;
    private javax.swing.JTextField txtNovaAdresa;
    private javax.swing.JTextField txtNovoMesto;
    private javax.swing.JTextField txtPretragaPoID;
    private javax.swing.JTextField txtPretraziMesto;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluMesta() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_MESTA);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Mesto> mesta = (ArrayList<Mesto>) so.getOdgovor();

        tblMesta.removeAll();

         
        TabelaMesto tm = (TabelaMesto) tblMesta.getModel();
        tm.setMesta(mesta);
    }
}
