/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.Vozilo;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.TabelaVozilo;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class FormaVozilo extends javax.swing.JFrame {

    /**
     * Creates new form FormaVozilo
     */
    public FormaVozilo() {
        initComponents();
        setLocationRelativeTo(null);
        tblVozila.setModel(new TabelaVozilo());
        
        popuniTabeluVozila();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVozila = new javax.swing.JTable();
        btnNazad = new javax.swing.JButton();
        btnKreirajNovoVozilo = new javax.swing.JButton();
        btnOsveziTabeluVozila = new javax.swing.JButton();
        btnIzmeniVozilo = new javax.swing.JButton();
        btnObrisiVozilo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPretraziVozilo = new javax.swing.JTextField();
        btnPretraziVozilo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVozila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVozila);

        btnNazad.setText("Back");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnKreirajNovoVozilo.setText("Add new");
        btnKreirajNovoVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajNovoVoziloActionPerformed(evt);
            }
        });

        btnOsveziTabeluVozila.setText("Refresh");
        btnOsveziTabeluVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluVozilaActionPerformed(evt);
            }
        });

        btnIzmeniVozilo.setText("Change");
        btnIzmeniVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniVoziloActionPerformed(evt);
            }
        });

        btnObrisiVozilo.setText("Delete");
        btnObrisiVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiVoziloActionPerformed(evt);
            }
        });

        jLabel1.setText("Search vehicle:");

        btnPretraziVozilo.setText("Search");
        btnPretraziVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziVoziloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNazad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPretraziVozilo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOsveziTabeluVozila)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmeniVozilo)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiVozilo)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnKreirajNovoVozilo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPretraziVozilo)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajNovoVozilo)
                    .addComponent(btnOsveziTabeluVozila)
                    .addComponent(btnIzmeniVozilo)
                    .addComponent(btnObrisiVozilo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraziVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziVozilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        GlavnaForma gf = new GlavnaForma();
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnKreirajNovoVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajNovoVoziloActionPerformed
        DialogKreirajVozilo dkv = new DialogKreirajVozilo(this, true);
        dkv.setVisible(true);
    }//GEN-LAST:event_btnKreirajNovoVoziloActionPerformed

    private void btnOsveziTabeluVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluVozilaActionPerformed
        popuniTabeluVozila();
    }//GEN-LAST:event_btnOsveziTabeluVozilaActionPerformed

    private void btnObrisiVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiVoziloActionPerformed
        int row = tblVozila.getSelectedRow();

        if (row != -1) {
            TabelaVozilo mt = (TabelaVozilo) tblVozila.getModel();
            Object id = tblVozila.getValueAt(row, 0);
            mt.obrisiVozilo(row);

            

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_VOZILO);
            kz.setParametar(id);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            mt.fireTableDataChanged();

            boolean obrisan = (boolean) so.getOdgovor();

            if (obrisan) {
                JOptionPane.showMessageDialog(this, "Vehicle deleted!");

                

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnObrisiVoziloActionPerformed

    private void btnIzmeniVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniVoziloActionPerformed
        int row = tblVozila.getSelectedRow();
        if (row != -1) {
            TabelaVozilo tv = (TabelaVozilo) tblVozila.getModel();
            int id = (int) tblVozila.getValueAt(row, 0);
            String model = (String) tblVozila.getValueAt(row, 1);              // Ime je u koloni 1
            double cena = (Double) tblVozila.getValueAt(row, 2);          // Prezime je u koloni 2
            String karoserija = (String) tblVozila.getValueAt(row, 3);
            String konjaza = (String) tblVozila.getValueAt(row, 4);
            String kubikaza = (String) tblVozila.getValueAt(row, 5);
            String boja = (String) tblVozila.getValueAt(row, 6);

            DialogIzmeniVozilo div = new DialogIzmeniVozilo(this, true);
            
            div.postaviId(id);
            div.postaviModel(model);
            div.postaviCenu(cena);
            div.postaviKaroseriju(karoserija);
            div.postaviKonjazu(konjaza);
            div.postaviKubikazu(kubikaza);
            div.postaviBoju(boja);
            
            
            div.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnIzmeniVoziloActionPerformed

    private void btnPretraziVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziVoziloActionPerformed
        if(txtPretraziVozilo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter vehicle!");
            return;
        }
        
        String model = txtPretraziVozilo.getText();
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_VOZILA);
        kz.setParametar(model);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Vozilo> pretraziV = (ArrayList<Vozilo>) so.getOdgovor();

        tblVozila.removeAll();

         
        TabelaVozilo tv = (TabelaVozilo) tblVozila.getModel();
        tv.setPretragaVozila(pretraziV);
    }//GEN-LAST:event_btnPretraziVoziloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaVozilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniVozilo;
    private javax.swing.JButton btnKreirajNovoVozilo;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiVozilo;
    private javax.swing.JButton btnOsveziTabeluVozila;
    private javax.swing.JButton btnPretraziVozilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVozila;
    private javax.swing.JTextField txtPretraziVozilo;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluVozila() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_VOZILA);
        

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Vozilo> vozilo = (ArrayList<Vozilo>) so.getOdgovor();

        tblVozila.removeAll();

         
        TabelaVozilo tv = (TabelaVozilo) tblVozila.getModel();
        tv.setVozilo(vozilo);
    }
}
