/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.Zaposleni;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.TabelaZaposleni;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class FormaZaposleni extends javax.swing.JFrame {

    /**
     * Creates new form FormaZaposleni
     */
    public FormaZaposleni() {
        initComponents();
        setLocationRelativeTo(null);
        tblZaposleni.setModel(new TabelaZaposleni());
        
        popuniTabeluZaposleni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaposleni = new javax.swing.JTable();
        btnObrisiZaposlenog = new javax.swing.JButton();
        btnIzmeniZaposlenog = new javax.swing.JButton();
        txtUnesiImeZaposlenog = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPretragaZaposlenog = new javax.swing.JButton();
        btnDodajNovogZaposlenog = new javax.swing.JButton();
        btnOsveziTabeluZaposlenih = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employees");

        tblZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZaposleni);

        btnObrisiZaposlenog.setText("Delete employee");
        btnObrisiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZaposlenogActionPerformed(evt);
            }
        });

        btnIzmeniZaposlenog.setText("Make changes");
        btnIzmeniZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniZaposlenogActionPerformed(evt);
            }
        });

        jLabel1.setText(" Insert name:");

        btnPretragaZaposlenog.setText("Search");
        btnPretragaZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaZaposlenogActionPerformed(evt);
            }
        });

        btnDodajNovogZaposlenog.setText("Add new");
        btnDodajNovogZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovogZaposlenogActionPerformed(evt);
            }
        });

        btnOsveziTabeluZaposlenih.setText("Refresh table");
        btnOsveziTabeluZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluZaposlenihActionPerformed(evt);
            }
        });

        btnNazad.setText("Back");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtUnesiImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIzmeniZaposlenog)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiZaposlenog)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnNazad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajNovogZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(btnPretragaZaposlenog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnOsveziTabeluZaposlenih))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiZaposlenog)
                    .addComponent(btnIzmeniZaposlenog)
                    .addComponent(btnOsveziTabeluZaposlenih))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUnesiImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretragaZaposlenog))
                .addGap(18, 18, 18)
                .addComponent(btnDodajNovogZaposlenog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnNazad)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNovogZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovogZaposlenogActionPerformed
        DialogKreirajZaposlenog dkz = new DialogKreirajZaposlenog(this, true);
        dkz.setVisible(true);
    }//GEN-LAST:event_btnDodajNovogZaposlenogActionPerformed

    private void btnOsveziTabeluZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluZaposlenihActionPerformed
        popuniTabeluZaposleni();
    }//GEN-LAST:event_btnOsveziTabeluZaposlenihActionPerformed

    private void btnObrisiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZaposlenogActionPerformed
        int row = tblZaposleni.getSelectedRow();

        if (row != -1) {
            TabelaZaposleni mt = (TabelaZaposleni) tblZaposleni.getModel();
            Object id = tblZaposleni.getValueAt(row, 0);
            mt.obrisiZaposlenog(row);

            

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_ZAPOSLENOG);
            kz.setParametar(id);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            mt.fireTableDataChanged();

            boolean obrisan = (boolean) so.getOdgovor();

            if (obrisan) {
                JOptionPane.showMessageDialog(this, "Employee deleted!");

                

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }

        
        
    }//GEN-LAST:event_btnObrisiZaposlenogActionPerformed

    private void btnIzmeniZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniZaposlenogActionPerformed
        int row = tblZaposleni.getSelectedRow();
        if (row != -1) {
            
            int id = (int) tblZaposleni.getValueAt(row, 0);
            String ime = (String) tblZaposleni.getValueAt(row, 1);              // Ime je u koloni 1
            String prezime = (String) tblZaposleni.getValueAt(row, 2);          // Prezime je u koloni 2
            String korisnickoIme = (String) tblZaposleni.getValueAt(row, 3);    // Korisničko ime je u koloni 3

            DialogIzmeniZaposlenog diz = new DialogIzmeniZaposlenog(this, true);
            
            diz.postaviId(id);
            diz.postaviIme(ime);
            diz.postaviPrezime(prezime);
            diz.postaviKorisnickoIme(korisnickoIme);
            
            
            diz.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }

        
    }//GEN-LAST:event_btnIzmeniZaposlenogActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        GlavnaForma gf = new GlavnaForma();
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnPretragaZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaZaposlenogActionPerformed
        
        if(txtUnesiImeZaposlenog.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter employee!");
            return;
        }
        
        String ime = txtUnesiImeZaposlenog.getText();
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_ZAPOSLENE);
        kz.setParametar(ime);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Zaposleni> pretrazeniZ = (ArrayList<Zaposleni>) so.getOdgovor();

        tblZaposleni.removeAll();

         
        TabelaZaposleni tz = (TabelaZaposleni) tblZaposleni.getModel();
        tz.setPretragaZaposleni(pretrazeniZ);
        
    }//GEN-LAST:event_btnPretragaZaposlenogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaZaposleni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNovogZaposlenog;
    private javax.swing.JButton btnIzmeniZaposlenog;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiZaposlenog;
    private javax.swing.JButton btnOsveziTabeluZaposlenih;
    private javax.swing.JButton btnPretragaZaposlenog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZaposleni;
    private javax.swing.JTextField txtUnesiImeZaposlenog;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluZaposleni() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_ZAPOSLENE);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Zaposleni> zaposleni = (ArrayList<Zaposleni>) so.getOdgovor();

        tblZaposleni.removeAll();

         
        TabelaZaposleni tz = (TabelaZaposleni) tblZaposleni.getModel();
        tz.setZaposleni(zaposleni);
    
        
        
        
    }
}
