/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.Rezervacija;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.TabelaRezervacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class FormaPrikazRezervacija extends javax.swing.JFrame {

    /**
     * Creates new form FormaPrikazRezervacija
     */
    
    
    
    public FormaPrikazRezervacija() {
        initComponents();
        setLocationRelativeTo(null);
        tblRezervacije.setModel(new TabelaRezervacija());
        
        
        popuniTabeluRez();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnKreirajRezervaciju = new javax.swing.JButton();
        btnDodajStavkeRez = new javax.swing.JButton();
        btnOsveziTabeluRez = new javax.swing.JButton();
        btnObrisiRez = new javax.swing.JButton();
        btnPretraziRezervaciju = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ftxtDatumUzimanja = new javax.swing.JFormattedTextField();
        btnIzmeniRez = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezervacije);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnKreirajRezervaciju.setText("Create Reservation");
        btnKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajRezervacijuActionPerformed(evt);
            }
        });

        btnDodajStavkeRez.setText("Add item for reservation");
        btnDodajStavkeRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkeRezActionPerformed(evt);
            }
        });

        btnOsveziTabeluRez.setText("Refresh table");
        btnOsveziTabeluRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluRezActionPerformed(evt);
            }
        });

        btnObrisiRez.setText("Delete");
        btnObrisiRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiRezActionPerformed(evt);
            }
        });

        btnPretraziRezervaciju.setText("Search");
        btnPretraziRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziRezervacijuActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter date:");

        ftxtDatumUzimanja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        btnIzmeniRez.setText("Make Changes");
        btnIzmeniRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniRezActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKreirajRezervaciju)
                                .addGap(18, 18, 18)
                                .addComponent(btnDodajStavkeRez, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtDatumUzimanja)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraziRezervaciju)))
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiRez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIzmeniRez, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(btnOsveziTabeluRez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajRezervaciju)
                    .addComponent(btnDodajStavkeRez)
                    .addComponent(btnObrisiRez)
                    .addComponent(btnIzmeniRez))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraziRezervaciju)
                    .addComponent(jLabel2)
                    .addComponent(ftxtDatumUzimanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOsveziTabeluRez))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GlavnaForma gf = new GlavnaForma();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajRezervacijuActionPerformed
        DialogKreirajRezervaciju dkr = new DialogKreirajRezervaciju(this, true);
        dkr.setVisible(true);
    }//GEN-LAST:event_btnKreirajRezervacijuActionPerformed

    private void btnDodajStavkeRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkeRezActionPerformed
        int row = tblRezervacije.getSelectedRow();

        if (row != -1) {
            
            int id = (int)tblRezervacije.getValueAt(row, 0);
            
             

            DialogKreirajStavkuRez dksr = new DialogKreirajStavkuRez(this, true);
            dksr.postaviId(id);
           
            
            dksr.setVisible(true);

            
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnDodajStavkeRezActionPerformed

    private void btnOsveziTabeluRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluRezActionPerformed
        
        popuniTabeluRez();
        
    }//GEN-LAST:event_btnOsveziTabeluRezActionPerformed

    private void btnObrisiRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiRezActionPerformed
        
        int row = tblRezervacije.getSelectedRow();

        if (row != -1) {
            TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
            Object id = tblRezervacije.getValueAt(row, 0);
            tr.obrisiRez(row);

            

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_REZERVACIJU);
            kz.setParametar(id);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            tr.fireTableDataChanged();

            boolean obrisan = (boolean) so.getOdgovor();

            if (obrisan) {
                JOptionPane.showMessageDialog(this, "Reservation deleted!");

                

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnObrisiRezActionPerformed

    private void btnPretraziRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziRezervacijuActionPerformed
        
        if(ftxtDatumUzimanja.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter date!");
            return;
        }
        
        LocalDate datum = LocalDate.parse(ftxtDatumUzimanja.getText());
        
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_REZERVACIJE);
        kz.setParametar(datum);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Rezervacija> pretrazeneRez = (ArrayList<Rezervacija>) so.getOdgovor();

        tblRezervacije.removeAll();

         
        TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
        tr.setPretragaRez(pretrazeneRez);
    }//GEN-LAST:event_btnPretraziRezervacijuActionPerformed

    private void btnIzmeniRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniRezActionPerformed
        
        int row = tblRezervacije.getSelectedRow();
        if (row != -1) {
            
            int id =  (int) tblRezervacije.getValueAt(row, 0);
            
            DialogIzmeniRezervaciju dir = new DialogIzmeniRezervaciju(this, false, id);
            
            dir.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnIzmeniRezActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPrikazRezervacija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavkeRez;
    private javax.swing.JButton btnIzmeniRez;
    private javax.swing.JButton btnKreirajRezervaciju;
    private javax.swing.JButton btnObrisiRez;
    private javax.swing.JButton btnOsveziTabeluRez;
    private javax.swing.JButton btnPretraziRezervaciju;
    private javax.swing.JFormattedTextField ftxtDatumUzimanja;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRezervacije;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluRez() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_REZERVACIJE);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Rezervacija> rez = (ArrayList<Rezervacija>) so.getOdgovor();

        tblRezervacije.removeAll();

         
        TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
        tr.setRez(rez);
    }

    
}
