/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.RadnaSmena;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.TabelaRadnaSmena;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class FormaRadnaSmena extends javax.swing.JFrame {

    /**
     * Creates new form FormaRadnaSmena
     */
    public FormaRadnaSmena() {
        initComponents();
        setLocationRelativeTo(null);
        tblRadnaSmena.setModel(new TabelaRadnaSmena());
        
        popuniTabeluRS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRadnaSmena = new javax.swing.JTable();
        btnObrisiSmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftxtPocetakSmene = new javax.swing.JFormattedTextField();
        btnPretraziSmene = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftxtNovaSmenaPocetak = new javax.swing.JFormattedTextField();
        ftxtNovaSmenaKraj = new javax.swing.JFormattedTextField();
        btnKreirajSmenu = new javax.swing.JButton();
        btnOsveziTabelu = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnIzmeniSmenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRSPretragaID = new javax.swing.JTextField();
        btnPretragaSmeneID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Work Shifts");

        tblRadnaSmena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRadnaSmena);

        btnObrisiSmenu.setText("Delete");
        btnObrisiSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiSmenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Search shift");

        jLabel2.setText("Shift start:");

        ftxtPocetakSmene.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));

        btnPretraziSmene.setText("Search");
        btnPretraziSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziSmeneActionPerformed(evt);
            }
        });

        jLabel3.setText("Insert new shift");

        jLabel4.setText("Shift start:");

        jLabel5.setText("Shift end:");

        ftxtNovaSmenaPocetak.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));

        ftxtNovaSmenaKraj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));

        btnKreirajSmenu.setText("Insert shift");
        btnKreirajSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajSmenuActionPerformed(evt);
            }
        });

        btnOsveziTabelu.setText("Refresh table");
        btnOsveziTabelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluActionPerformed(evt);
            }
        });

        btnNazad.setText("Back");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnIzmeniSmenu.setText("Change");
        btnIzmeniSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniSmenuActionPerformed(evt);
            }
        });

        jLabel6.setText("Shift ID:");

        btnPretragaSmeneID.setText("Search");
        btnPretragaSmeneID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaSmeneIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtNovaSmenaPocetak)
                            .addComponent(ftxtNovaSmenaKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOsveziTabelu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnKreirajSmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnIzmeniSmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(30, 30, 30)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ftxtPocetakSmene, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(txtRSPretragaID))
                                    .addGap(44, 44, 44)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPretraziSmene, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(btnNazad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisiSmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPretragaSmeneID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiSmenu)
                    .addComponent(btnIzmeniSmenu))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftxtPocetakSmene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziSmene))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRSPretragaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretragaSmeneID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtNovaSmenaPocetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtNovaSmenaKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnKreirajSmenu))
                .addGap(18, 18, 18)
                .addComponent(btnOsveziTabelu)
                .addGap(66, 66, 66)
                .addComponent(btnNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajSmenuActionPerformed
       
        
        if (ftxtNovaSmenaPocetak.getText().isEmpty() || ftxtNovaSmenaKraj.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!");
            return;
        }

        LocalTime pocetakNove = LocalTime.parse(ftxtNovaSmenaPocetak.getText());
        LocalTime krajNove = LocalTime.parse(ftxtNovaSmenaKraj.getText());
        
        
        RadnaSmena rs = new RadnaSmena(-1, pocetakNove, krajNove);

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.DODAJ_RS);
        kz.setParametar(rs);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) so.getOdgovor();

        if (uspesno) {
            JOptionPane.showMessageDialog(this, "New shift created!");
            
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnKreirajSmenuActionPerformed

    private void btnOsveziTabeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluActionPerformed
        popuniTabeluRS();
    }//GEN-LAST:event_btnOsveziTabeluActionPerformed

    private void btnObrisiSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiSmenuActionPerformed
        
        int row = tblRadnaSmena.getSelectedRow();

        if (row != -1) {
            TabelaRadnaSmena mt = (TabelaRadnaSmena) tblRadnaSmena.getModel();
            Object id = tblRadnaSmena.getValueAt(row, 0);
            mt.obrisiSmenu(row);

            

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_RS);
            kz.setParametar(id);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            mt.fireTableDataChanged();

            boolean obrisan = (boolean) so.getOdgovor();

            if (obrisan) {
                JOptionPane.showMessageDialog(this, "Shift deleted!");

                

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnObrisiSmenuActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        GlavnaForma gf = new GlavnaForma();
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnIzmeniSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniSmenuActionPerformed
        
        int row = tblRadnaSmena.getSelectedRow();
        if (row != -1) {
            
            int id = (int) tblRadnaSmena.getValueAt(row, 0);
            LocalTime pocetak =  (LocalTime) tblRadnaSmena.getValueAt(row, 1);              // pocetak smene kolona 1
            LocalTime kraj =  (LocalTime) tblRadnaSmena.getValueAt(row, 2);          // kraj smene kolona 2
                

            DialogIzmeniSmenu dirs = new DialogIzmeniSmenu(this, true);
            
            dirs.postaviId(id);
            dirs.postaviPocetak(pocetak);
            dirs.postaviKraj(kraj);
            
            
            
            dirs.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnIzmeniSmenuActionPerformed

    private void btnPretraziSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziSmeneActionPerformed
        if(ftxtPocetakSmene.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter time!");
            return;
        }
        
        
        String pocetak = ftxtPocetakSmene.getText();
        
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_SMENE);
        kz.setParametar(pocetak);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<RadnaSmena> pretrazeneRS = (ArrayList<RadnaSmena>) so.getOdgovor();

        tblRadnaSmena.removeAll();

         
        TabelaRadnaSmena trs = (TabelaRadnaSmena) tblRadnaSmena.getModel();
        trs.setPretragaRS(pretrazeneRS);
    }//GEN-LAST:event_btnPretraziSmeneActionPerformed

    private void btnPretragaSmeneIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaSmeneIDActionPerformed
        if(txtRSPretragaID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter shift ID!");
            return;
        }
        
        int id = Integer.parseInt(txtRSPretragaID.getText());
        
        
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_IDSMENE);
        kz.setParametar(id);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        
        
        ArrayList<RadnaSmena> pretraziRS = (ArrayList<RadnaSmena>) so.getOdgovor();

        tblRadnaSmena.removeAll();

        
         
        TabelaRadnaSmena trs = (TabelaRadnaSmena) tblRadnaSmena.getModel();
        trs.setPretragaRS(pretraziRS);
    }//GEN-LAST:event_btnPretragaSmeneIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaRadnaSmena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniSmenu;
    private javax.swing.JButton btnKreirajSmenu;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiSmenu;
    private javax.swing.JButton btnOsveziTabelu;
    private javax.swing.JButton btnPretragaSmeneID;
    private javax.swing.JButton btnPretraziSmene;
    private javax.swing.JFormattedTextField ftxtNovaSmenaKraj;
    private javax.swing.JFormattedTextField ftxtNovaSmenaPocetak;
    private javax.swing.JFormattedTextField ftxtPocetakSmene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRadnaSmena;
    private javax.swing.JTextField txtRSPretragaID;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluRS() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.POPUNI_RS);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<RadnaSmena> rs = (ArrayList<RadnaSmena>) so.getOdgovor();

        tblRadnaSmena.removeAll();

         
        TabelaRadnaSmena trs = (TabelaRadnaSmena) tblRadnaSmena.getModel();
        trs.setRadnaSmena(rs);
    }
}
