/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klase.Klijent;
import klase.Rezervacija;
import klase.Vozilo;
import klase.Zaposleni;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.TabelaRezervacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miloš
 */
public class FormaPrikazRezervacija extends javax.swing.JFrame {

    /**
     * Creates new form FormaPrikazRezervacija
     */
    
    
    
    public FormaPrikazRezervacija() {
        initComponents();
        setLocationRelativeTo(null);
        tblRezervacije.setModel(new TabelaRezervacija());
        
        
        popuniTabeluRez();
        popuniCBVozila();
        popuniCBKlijent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnKreirajRezervaciju = new javax.swing.JButton();
        btnOsveziTabeluRez = new javax.swing.JButton();
        btnObrisiRez = new javax.swing.JButton();
        btnPretraziRezervaciju = new javax.swing.JButton();
        btnIzmeniRez = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPretragaRezPoID = new javax.swing.JButton();
        txtPretragaRezID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPretragaPoZaposlenom = new javax.swing.JTextField();
        btnVidiStavkeRez = new javax.swing.JButton();
        btnPrikaziStavkeRez = new javax.swing.JButton();
        cbVozila = new javax.swing.JComboBox<>();
        cbKlijent = new javax.swing.JComboBox<>();
        btnPretraziPoKlijentuIliModelu = new javax.swing.JButton();
        btnPretragaPoModel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezervacije);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnKreirajRezervaciju.setText("Create Reservation");
        btnKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajRezervacijuActionPerformed(evt);
            }
        });

        btnOsveziTabeluRez.setText("Refresh table");
        btnOsveziTabeluRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluRezActionPerformed(evt);
            }
        });

        btnObrisiRez.setText("Delete");
        btnObrisiRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiRezActionPerformed(evt);
            }
        });

        btnPretraziRezervaciju.setText("Search");
        btnPretraziRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziRezervacijuActionPerformed(evt);
            }
        });

        btnIzmeniRez.setText("Make Changes");
        btnIzmeniRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniRezActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter ID:");

        btnPretragaRezPoID.setText("Search");
        btnPretragaRezPoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaRezPoIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Insert one of the following:");

        jLabel6.setText("Employee ID:");

        txtPretragaPoZaposlenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaPoZaposlenomActionPerformed(evt);
            }
        });

        btnVidiStavkeRez.setText("All items");
        btnVidiStavkeRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVidiStavkeRezActionPerformed(evt);
            }
        });

        btnPrikaziStavkeRez.setText("Show reservation items");
        btnPrikaziStavkeRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkeRezActionPerformed(evt);
            }
        });

        cbVozila.setToolTipText("");

        btnPretraziPoKlijentuIliModelu.setText("Search");
        btnPretraziPoKlijentuIliModelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPoKlijentuIliModeluActionPerformed(evt);
            }
        });

        btnPretragaPoModel.setText("Search");
        btnPretragaPoModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaPoModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKreirajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnObrisiRez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmeniRez, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrikaziStavkeRez, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOsveziTabeluRez, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnVidiStavkeRez, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPretragaPoZaposlenom, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtPretragaRezID, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbKlijent, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbVozila, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPretraziPoKlijentuIliModelu)
                                    .addComponent(btnPretragaPoModel))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPretraziRezervaciju, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPretragaRezPoID, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(btnVidiStavkeRez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajRezervaciju)
                    .addComponent(btnObrisiRez)
                    .addComponent(btnOsveziTabeluRez)
                    .addComponent(btnIzmeniRez)
                    .addComponent(btnPrikaziStavkeRez))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretragaPoModel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziPoKlijentuIliModelu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPretragaPoZaposlenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziRezervaciju))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretragaRezPoID)
                    .addComponent(jLabel3)
                    .addComponent(txtPretragaRezID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        cbVozila.getAccessibleContext().setAccessibleName("Select Model");
        cbKlijent.getAccessibleContext().setAccessibleName("Select Client ID");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GlavnaForma gf = new GlavnaForma();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajRezervacijuActionPerformed
        DialogKreirajRezervaciju dkr = new DialogKreirajRezervaciju(this, true);
        dkr.setVisible(true);
    }//GEN-LAST:event_btnKreirajRezervacijuActionPerformed

    private void btnOsveziTabeluRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluRezActionPerformed
        
        popuniTabeluRez();
        
    }//GEN-LAST:event_btnOsveziTabeluRezActionPerformed

    private void btnObrisiRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiRezActionPerformed
        
        int row = tblRezervacije.getSelectedRow();

        if (row != -1) {
            TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
            int id = (int) tblRezervacije.getValueAt(row, 0);
            tr.obrisiRez(row);

            Rezervacija r = new Rezervacija(id, null, null, 0, -1, -1, null);

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_REZERVACIJU);
            kz.setParametar(r);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            tr.fireTableDataChanged();

            boolean obrisan = (boolean) so.getOdgovor();

            if (obrisan) {
                JOptionPane.showMessageDialog(this, "Reservation deleted!");

                

            } else {
                JOptionPane.showMessageDialog(this, "Error deleting reservation!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnObrisiRezActionPerformed

    private void btnPretraziRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziRezervacijuActionPerformed
        
        
        
//        if(!(txtPretragaPoKlijentuIliModelu.getText().isEmpty())){
//            String modelKlijent = txtPretragaPoKlijentuIliModelu.getText();
//
//            KlijentskiZahtev kz = new KlijentskiZahtev();
//            kz.setOperacija(Operacije.PRETRAZI_REZERVACIJE_PO_MODELU_ILI_KLIJENTU);
//            kz.setParametar(modelKlijent);
//
//            Komunikacija.getInstance().posaljiZahtev(kz);
            
        int idZap = Integer.parseInt(txtPretragaPoZaposlenom.getText());

        Rezervacija r = new Rezervacija(-1, null, null, 0, -1, idZap, null);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_REZERVACIJE_PO_ZAP);
        kz.setParametar(r);

        Komunikacija.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Rezervacija> pretrazeneRez = (ArrayList<Rezervacija>) so.getOdgovor();

        tblRezervacije.removeAll();

        TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
        tr.setPretragaRez(pretrazeneRez);
    }//GEN-LAST:event_btnPretraziRezervacijuActionPerformed

    private void btnIzmeniRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniRezActionPerformed
        
        int row = tblRezervacije.getSelectedRow();
        if (row != -1) {
            
            int id =  (int) tblRezervacije.getValueAt(row, 0);
            
//            LocalDate uzimanje = LocalDate.parse( (String) tblRezervacije.getValueAt(row, 1));              
//            LocalDate vracanje = LocalDate.parse( (String) tblRezervacije.getValueAt(row, 2));           
            
            
            
            DialogPromeniUnosRezervacije dpur = new DialogPromeniUnosRezervacije(this, true, id);
            
            dpur.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
        

    }//GEN-LAST:event_btnIzmeniRezActionPerformed

    private void btnPretragaRezPoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaRezPoIDActionPerformed
        if(txtPretragaRezID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter value!");
            return;
        }
        
        int id = Integer.parseInt(txtPretragaRezID.getText());
        
        Rezervacija r = new Rezervacija(id, null, null, 0, -1, -1, null);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAZI_REZERVACIJUID);
        kz.setParametar(r);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        
        
        ArrayList<Rezervacija> pretraziR = (ArrayList<Rezervacija>) so.getOdgovor();

        tblRezervacije.removeAll();

        
         
        TabelaRezervacija trez = (TabelaRezervacija) tblRezervacije.getModel();
        trez.setPretragaRez(pretraziR);
    }//GEN-LAST:event_btnPretragaRezPoIDActionPerformed

    private void txtPretragaPoZaposlenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaPoZaposlenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaPoZaposlenomActionPerformed

    private void btnVidiStavkeRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVidiStavkeRezActionPerformed
        
        
            
            DialogIzmeniRezervaciju dir = new DialogIzmeniRezervaciju(this, false);
            
            dir.setVisible(true);

        
    }//GEN-LAST:event_btnVidiStavkeRezActionPerformed

    private void btnPrikaziStavkeRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkeRezActionPerformed
        int row = tblRezervacije.getSelectedRow();
        if (row != -1) {
            
            int id =  (int) tblRezervacije.getValueAt(row, 0);
            
//            LocalDate uzimanje = LocalDate.parse( (String) tblRezervacije.getValueAt(row, 1));              
//            LocalDate vracanje = LocalDate.parse( (String) tblRezervacije.getValueAt(row, 2));           
            
            
            
            DialogPrikaziStavkeRez dpsr = new DialogPrikaziStavkeRez(this, true, id);
            
            dpsr.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Element not selected!");
        }
    }//GEN-LAST:event_btnPrikaziStavkeRezActionPerformed

    private void btnPretraziPoKlijentuIliModeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPoKlijentuIliModeluActionPerformed
        


        
            Klijent k = (Klijent) cbKlijent.getSelectedItem();
            int idK = k.getIdKlijent();
            
            Rezervacija r = new Rezervacija(-1, null, null, 0, idK, -1, null);
            
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.PRETRAZI_REZERVACIJE_PO_KLIJENTU);
            kz.setParametar(r);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            ArrayList<Rezervacija> rez = (ArrayList<Rezervacija>) so.getOdgovor();

            tblRezervacije.removeAll();

            TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
            tr.setRez(rez);
        


    }//GEN-LAST:event_btnPretraziPoKlijentuIliModeluActionPerformed

    private void btnPretragaPoModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaPoModelActionPerformed
                
            Vozilo v = (Vozilo) cbVozila.getSelectedItem();
            String model=v.getModel();
            int idvoz = v.getIdVozilo();
            
            Rezervacija r = new Rezervacija(-1, null, null, 0, -1, -1, v);
            
            
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.PRETRAZI_REZERVACIJE_PO_MODELU);
            kz.setParametar(r);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            
            ArrayList<Rezervacija> rez = (ArrayList<Rezervacija>) so.getOdgovor();

            tblRezervacije.removeAll();

            TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
            tr.setRez(rez);
            
        
    }//GEN-LAST:event_btnPretragaPoModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPrikazRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPrikazRezervacija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniRez;
    private javax.swing.JButton btnKreirajRezervaciju;
    private javax.swing.JButton btnObrisiRez;
    private javax.swing.JButton btnOsveziTabeluRez;
    private javax.swing.JButton btnPretragaPoModel;
    private javax.swing.JButton btnPretragaRezPoID;
    private javax.swing.JButton btnPretraziPoKlijentuIliModelu;
    private javax.swing.JButton btnPretraziRezervaciju;
    private javax.swing.JButton btnPrikaziStavkeRez;
    private javax.swing.JButton btnVidiStavkeRez;
    private javax.swing.JComboBox<Klijent> cbKlijent;
    private javax.swing.JComboBox<Vozilo> cbVozila;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRezervacije;
    private javax.swing.JTextField txtPretragaPoZaposlenom;
    private javax.swing.JTextField txtPretragaRezID;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluRez() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_REZERVACIJE);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Rezervacija> rez = (ArrayList<Rezervacija>) so.getOdgovor();

        tblRezervacije.removeAll();

         
        TabelaRezervacija tr = (TabelaRezervacija) tblRezervacije.getModel();
        tr.setRez(rez);
    }

    private void popuniCBVozila() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_VOZILA);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Vozilo> vozila = (ArrayList<Vozilo>) so.getOdgovor();

        cbVozila.removeAllItems();

        for (Vozilo v : vozila) {
            cbVozila.addItem(v);
        }
    }

    private void popuniCBKlijent() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_KLIJENTE);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Klijent> klijenti = (ArrayList<Klijent>) so.getOdgovor();

        cbKlijent.removeAllItems();

        for (Klijent k : klijenti) {
            cbKlijent.addItem(k);
        }
    }

    
}
