/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;



/**
 *
 * @author Miloš
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnZaposleni = new javax.swing.JButton();
        btnRadneSmene = new javax.swing.JButton();
        btnKlijenti = new javax.swing.JButton();
        btnRaspored = new javax.swing.JButton();
        btnMesta = new javax.swing.JButton();
        btnVozila = new javax.swing.JButton();
        btnRezervacije = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");

        jLabel1.setText("Rent A Car Software");

        btnZaposleni.setText("Employees");
        btnZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaposleniActionPerformed(evt);
            }
        });

        btnRadneSmene.setText("Work Shifts");
        btnRadneSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadneSmeneActionPerformed(evt);
            }
        });

        btnKlijenti.setText("Clients");
        btnKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentiActionPerformed(evt);
            }
        });

        btnRaspored.setText("Work Schedule");
        btnRaspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRasporedActionPerformed(evt);
            }
        });

        btnMesta.setText("Cities");
        btnMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMestaActionPerformed(evt);
            }
        });

        btnVozila.setText("Vehicles");
        btnVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVozilaActionPerformed(evt);
            }
        });

        btnRezervacije.setText("Reservations");
        btnRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervacijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRaspored, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(btnKlijenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRadneSmene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVozila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnZaposleni)
                .addGap(18, 18, 18)
                .addComponent(btnRadneSmene)
                .addGap(18, 18, 18)
                .addComponent(btnRaspored)
                .addGap(18, 18, 18)
                .addComponent(btnKlijenti)
                .addGap(18, 18, 18)
                .addComponent(btnMesta)
                .addGap(18, 18, 18)
                .addComponent(btnVozila)
                .addGap(18, 18, 18)
                .addComponent(btnRezervacije)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaposleniActionPerformed
        FormaZaposleni fz = new FormaZaposleni();
        fz.setVisible(true);
    }//GEN-LAST:event_btnZaposleniActionPerformed

    private void btnRadneSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadneSmeneActionPerformed
        FormaRadnaSmena frs = new FormaRadnaSmena();
        frs.setVisible(true);
    }//GEN-LAST:event_btnRadneSmeneActionPerformed

    private void btnRasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRasporedActionPerformed
        FormaZRS zrsf = new FormaZRS();
        zrsf.setVisible(true);
    }//GEN-LAST:event_btnRasporedActionPerformed

    private void btnMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMestaActionPerformed
        FormaMesto fm = new FormaMesto();
        fm.setVisible(true);
    }//GEN-LAST:event_btnMestaActionPerformed

    private void btnKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentiActionPerformed
        FormaKlijent fk = new FormaKlijent();
        fk.setVisible(true);
    }//GEN-LAST:event_btnKlijentiActionPerformed

    private void btnVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVozilaActionPerformed
        FormaVozilo fv = new FormaVozilo();
        fv.setVisible(true);
    }//GEN-LAST:event_btnVozilaActionPerformed

    private void btnRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervacijeActionPerformed
        FormaPrikazRezervacija fpr = new FormaPrikazRezervacija();
        fpr.setVisible(true);
    }//GEN-LAST:event_btnRezervacijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlijenti;
    private javax.swing.JButton btnMesta;
    private javax.swing.JButton btnRadneSmene;
    private javax.swing.JButton btnRaspored;
    private javax.swing.JButton btnRezervacije;
    private javax.swing.JButton btnVozila;
    private javax.swing.JButton btnZaposleni;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
